# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/huangyugen/Documents/cs projects/Kindred"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/huangyugen/Documents/cs projects/Kindred"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/huangyugen/Documents/cs projects/Kindred/CMakeFiles" "/Users/huangyugen/Documents/cs projects/Kindred//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/huangyugen/Documents/cs projects/Kindred/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

lexer.o: lexer.cpp.o
.PHONY : lexer.o

# target to build an object file
lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/lexer.cpp.o
.PHONY : lexer.cpp.o

lexer.i: lexer.cpp.i
.PHONY : lexer.i

# target to preprocess a source file
lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/lexer.cpp.i
.PHONY : lexer.cpp.i

lexer.s: lexer.cpp.s
.PHONY : lexer.s

# target to generate assembly for a file
lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/lexer.cpp.s
.PHONY : lexer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

parser.o: parser.cpp.o
.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i
.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/parser.cpp.s
.PHONY : parser.cpp.s

src/cfg_builder.o: src/cfg_builder.cpp.o
.PHONY : src/cfg_builder.o

# target to build an object file
src/cfg_builder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/cfg_builder.cpp.o
.PHONY : src/cfg_builder.cpp.o

src/cfg_builder.i: src/cfg_builder.cpp.i
.PHONY : src/cfg_builder.i

# target to preprocess a source file
src/cfg_builder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/cfg_builder.cpp.i
.PHONY : src/cfg_builder.cpp.i

src/cfg_builder.s: src/cfg_builder.cpp.s
.PHONY : src/cfg_builder.s

# target to generate assembly for a file
src/cfg_builder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/cfg_builder.cpp.s
.PHONY : src/cfg_builder.cpp.s

src/closure.o: src/closure.cpp.o
.PHONY : src/closure.o

# target to build an object file
src/closure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/closure.cpp.o
.PHONY : src/closure.cpp.o

src/closure.i: src/closure.cpp.i
.PHONY : src/closure.i

# target to preprocess a source file
src/closure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/closure.cpp.i
.PHONY : src/closure.cpp.i

src/closure.s: src/closure.cpp.s
.PHONY : src/closure.s

# target to generate assembly for a file
src/closure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/closure.cpp.s
.PHONY : src/closure.cpp.s

src/flowcheck.o: src/flowcheck.cpp.o
.PHONY : src/flowcheck.o

# target to build an object file
src/flowcheck.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/flowcheck.cpp.o
.PHONY : src/flowcheck.cpp.o

src/flowcheck.i: src/flowcheck.cpp.i
.PHONY : src/flowcheck.i

# target to preprocess a source file
src/flowcheck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/flowcheck.cpp.i
.PHONY : src/flowcheck.cpp.i

src/flowcheck.s: src/flowcheck.cpp.s
.PHONY : src/flowcheck.s

# target to generate assembly for a file
src/flowcheck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/flowcheck.cpp.s
.PHONY : src/flowcheck.cpp.s

src/ir_lower.o: src/ir_lower.cpp.o
.PHONY : src/ir_lower.o

# target to build an object file
src/ir_lower.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ir_lower.cpp.o
.PHONY : src/ir_lower.cpp.o

src/ir_lower.i: src/ir_lower.cpp.i
.PHONY : src/ir_lower.i

# target to preprocess a source file
src/ir_lower.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ir_lower.cpp.i
.PHONY : src/ir_lower.cpp.i

src/ir_lower.s: src/ir_lower.cpp.s
.PHONY : src/ir_lower.s

# target to generate assembly for a file
src/ir_lower.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ir_lower.cpp.s
.PHONY : src/ir_lower.cpp.s

src/liveness.o: src/liveness.cpp.o
.PHONY : src/liveness.o

# target to build an object file
src/liveness.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/liveness.cpp.o
.PHONY : src/liveness.cpp.o

src/liveness.i: src/liveness.cpp.i
.PHONY : src/liveness.i

# target to preprocess a source file
src/liveness.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/liveness.cpp.i
.PHONY : src/liveness.cpp.i

src/liveness.s: src/liveness.cpp.s
.PHONY : src/liveness.s

# target to generate assembly for a file
src/liveness.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/liveness.cpp.s
.PHONY : src/liveness.cpp.s

src/semerror.o: src/semerror.cpp.o
.PHONY : src/semerror.o

# target to build an object file
src/semerror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/semerror.cpp.o
.PHONY : src/semerror.cpp.o

src/semerror.i: src/semerror.cpp.i
.PHONY : src/semerror.i

# target to preprocess a source file
src/semerror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/semerror.cpp.i
.PHONY : src/semerror.cpp.i

src/semerror.s: src/semerror.cpp.s
.PHONY : src/semerror.s

# target to generate assembly for a file
src/semerror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/semerror.cpp.s
.PHONY : src/semerror.cpp.s

src/typecheck.o: src/typecheck.cpp.o
.PHONY : src/typecheck.o

# target to build an object file
src/typecheck.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/typecheck.cpp.o
.PHONY : src/typecheck.cpp.o

src/typecheck.i: src/typecheck.cpp.i
.PHONY : src/typecheck.i

# target to preprocess a source file
src/typecheck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/typecheck.cpp.i
.PHONY : src/typecheck.cpp.i

src/typecheck.s: src/typecheck.cpp.s
.PHONY : src/typecheck.s

# target to generate assembly for a file
src/typecheck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/typecheck.cpp.s
.PHONY : src/typecheck.cpp.s

src/visitor.o: src/visitor.cpp.o
.PHONY : src/visitor.o

# target to build an object file
src/visitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/visitor.cpp.o
.PHONY : src/visitor.cpp.o

src/visitor.i: src/visitor.cpp.i
.PHONY : src/visitor.i

# target to preprocess a source file
src/visitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/visitor.cpp.i
.PHONY : src/visitor.cpp.i

src/visitor.s: src/visitor.cpp.s
.PHONY : src/visitor.s

# target to generate assembly for a file
src/visitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/visitor.cpp.s
.PHONY : src/visitor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... src/cfg_builder.o"
	@echo "... src/cfg_builder.i"
	@echo "... src/cfg_builder.s"
	@echo "... src/closure.o"
	@echo "... src/closure.i"
	@echo "... src/closure.s"
	@echo "... src/flowcheck.o"
	@echo "... src/flowcheck.i"
	@echo "... src/flowcheck.s"
	@echo "... src/ir_lower.o"
	@echo "... src/ir_lower.i"
	@echo "... src/ir_lower.s"
	@echo "... src/liveness.o"
	@echo "... src/liveness.i"
	@echo "... src/liveness.s"
	@echo "... src/semerror.o"
	@echo "... src/semerror.i"
	@echo "... src/semerror.s"
	@echo "... src/typecheck.o"
	@echo "... src/typecheck.i"
	@echo "... src/typecheck.s"
	@echo "... src/visitor.o"
	@echo "... src/visitor.i"
	@echo "... src/visitor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

